#pragma once

#include "MVSConfig.h"
#include "WorkFlowObject.h"
#include "CameraObject.h"
#include "FrameObject.h"
#include "GlobalMapObject.h"

#include <QObject>
#include <opencv2/opencv.hpp>
#include <vector>
#include <sophus/se3.hpp>

/**
 * @brief the photographer class, generate frame with given cameras.
 */
class Photographer : public WorkFlowObject
{
	Q_OBJECT
public:
/**
 * @brief Photographer shared pointer type
 */
	using Ptr = std::shared_ptr<Photographer>;

	/**
	 * @brief create shared pointer of Photographer
	 * 
	 * @param Cameras camera lists
	 * @return Photographer::Ptr 
	 */
	static Photographer::Ptr Create(GlobalMapObject::Ptr Map, std::initializer_list<CameraObject::Ptr> Cameras);
public:
/**
 * @brief Construct a new Photographer object
 * 
 */
	Photographer();

	/**
	 * @brief Construct a new Photographer object with one camera
	 * 
	 * @param Camera camera pointer
	 */
	Photographer(CameraObject::Ptr Camera);

	/**
	 * @brief Construct a new Photographer object with multiple cameras
	 * 
	 * @param Cameras camera pointer lists
	 */
	Photographer(std::initializer_list<CameraObject::Ptr> Cameras);

	/**
	 * @brief Destroy the Photographer object
	 * 
	 */
	virtual ~Photographer();
	
public:
/**
 * @brief Get the Flow Name
 * 
 * @return std::string flow name
 */
	std::string type_name() override;

	/**
	 * @brief take a photo with given cameras
	 * 
	 * @param Frames output frames generated by the cameras
	 * @return true succeed
	 * @return false failed
	 */
	virtual bool Compute(std::vector<FrameObject::Ptr>& Frames);


	/**
	 * @brief clear the parameters of the flow, and deinitialize the flow
	 * 
	 * @return true succeed
	 * @return false failed
	 */
	virtual bool clear() override;

	virtual bool save(JsonNode& fs) override;
	virtual bool load(JsonNode& fs) override;

public slots:
	void Trigger() override;
	
	void Trigger(Photographer::DataQueue data);
	
protected:
	using CameraGroup = std::tuple<CameraObject::Ptr, Sophus::SE3d>;
	std::vector<CameraGroup> CamerasMap;
	//std::map<std::string,CameraGroup> CamerasMap;
	GlobalMapObject::Ptr GlobalMap;
};


class PinholePhotographer : public Photographer
{
	Q_OBJECT
public:
	using Ptr = std::shared_ptr<PinholePhotographer>;
	static PinholePhotographer::Ptr Create(GlobalMapObject::Ptr Map,std::initializer_list<CameraObject::Ptr> Cameras);
	
public:
	PinholePhotographer();
	PinholePhotographer(std::initializer_list<CameraObject::Ptr> Cameras);
	virtual ~PinholePhotographer();

public:
	bool Compute(std::vector<FrameObject::Ptr>& Frames) override;

public slots:
	void Trigger() override;
	void Trigger(Photographer::DataQueue data) override;
	
private:
	int FrameIDCounter = 0;
};